# Generated by Django 4.2 on 2023-05-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('forme', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('conditionnement', models.CharField(max_length=255)),
                ('prix_public', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remboursable', models.BooleanField()),
                ('tarif_reference', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
