# Generated by Django 4.2 on 2023-05-01 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_medicament_forme'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
