# Generated by Django 4.2 on 2023-05-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicament_nom'),
    ]

    operations = [
    ]
