# Generated by Django 4.2 on 2023-05-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_medicament_conditionnement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('type_de_maladie', models.CharField(blank=True, choices=[('c1', 'Type 1'), ('c2', 'Type 2'), ('c3', 'Type 3'), ('c4', 'Type 4'), ('c5', 'Type 5'), ('c6', 'Type 6'), ('c7', 'Type 7'), ('c8', 'Type 8'), ('c9', 'Type 9'), ('c10', 'Type 10'), ('c11', 'Type 11'), ('c12', 'Type 12'), ('c13', 'Type 13'), ('c14', 'Type 14'), ('c15', 'Type 15'), ('c16', 'Type 16'), ('c17', 'Type 17'), ('c18', 'Type 18'), ('c19', 'Type 19'), ('c20', 'Type 20'), ('c21', 'Type 21'), ('c22', 'Type 22'), ('c23', 'Type 23'), ('c24', 'Type 24'), ('c25', 'Type 25'), ('c26', 'Type 26'), ('c27', 'Type 27')], max_length=3, null=True)),
            ],
        ),
    ]
