# Generated by Django 4.2 on 2023-05-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_assure_type_de_maladie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assure',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
