# Generated by Django 4.2 on 2023-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_assure_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='id',
        ),
        migrations.AlterField(
            model_name='assure',
            name='matricule',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
